language: go
dist: bionic

go:
  - "1.14.x"

env:
  - GO111MODULE=on CODECOV_TOKEN=055ddb32-616a-4846-96fe-b68de18fa4bd

script:
  # - go test -covermode atomic -coverprofile coverage.txt .
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
