name: build
on:
  pull_request:
    branches: 
      - main
      - master
      - develop
  push:
    branches: 
      - main
      - master
      - develop
      - status-box
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: [1.14]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Running go tests
      env:
        GO111MODULE: on
      run: make tests
    - name: Coverage report upload
      uses: codecov/codecov-action@v1
      with: 
        fail_ci_if_error: false

  build:
    name: "Build package"
    needs: "test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        go: [1.14]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code
        uses: actions/checkout@master
      - name: Build
        env: 
          GO111MODULE: on
        run: make build
