name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - develop
      - refactor
  pull_request:
    branches:
      - '*'
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.36
          args: --issues-exit-code=1 --concurrency 8 --enable bodyclose,dogsled,dupl,errorlint,gocyclo,funlen,gocritic,godot,lll,misspell,unconvert,unparam,wrapcheck
          only-new-issues: true